### ISSUE TITLE
use of `block` in tasks breaks scanning

### ISSUE THREAD

**Issue by hunleyd** [xlab-steampunk/steampunk-scanner-cli#1]
Given the following task:
```
---
- block:
    - debug: var=foo
```
When I run `steampunk-scanner scan --tasks /tmp/foo.yml`, I should be getting:
```
/tmp/foo.yml:3: HINT: The 'debug' module is redirected to the 'ansible.builtin.debug' module. You should use fully-qualified collection name to avoid future problems.
```
In reality, I get:
```
/tmp/foo.yml:2: ERROR: Cannot find module information in the database. Is this a custom module not published on Ansible Galaxy?
```
Which presents 2 issues:
1) it doesn't understand `block` for some reason
2) scanning aborts when it hits a module it doesn't know about instead of noting it and continuing

**Comment by anzoman** [comment]
@hunleyd thanks for opening this, currently our Steampunk Scanner does not cover Ansible block syntax but we're working on it and will let you know when this is available.

**Comment by hunleyd** [comment]
excellent, thanks!
