### ISSUE TITLE
Add support for scanning of IaC directories

### ISSUE THREAD

**Issue by anzoman** [xlab-steampunk/steampunk-scanner-cli#12]
Currently, the [Steampunk Scanner CLI](https://pypi.org/project/steampunk-scanner/) works well on Ansible taskfiles, playbooks, roles and collections and the user needs to specify which one of those he is scanning with the corresponding CLI switch (e.g., `--playbooks`). 

In many occasions users have their own code structure (e.g., with Ansible playbooks located in different folders) that is a mixture of different tools and files. When these refer to configuration management, automation and orchestration this user's package is often called IaC (Infrastucture as Code) and users would want to scan their package regardless of the code structure and without the need to scan single playbooks and to specify their exact location. 

Nowadays many SAST and SCA tools (e.g., [Ansible Lint](
https://ansible-lint.readthedocs.io/en/latest/)) work in a way that they accept as an input a file directory or a compressed archive (e.g., zip, tgz) and then they search for the entities for scanning. The `steampunk-scanner` could work in a similar way so that we find playbooks, roles, collections and other Ansible entities within IaC, scan each of them and return the combined output. This could be the default scanning behavior (i.e., if the user doesn't use any of CLI flags) and would make the CLI easier to use and more flexible (e.g., we could integrate it better in [IaC Scan Runner](https://github.com/xlab-si/iac-scan-runner)).

cc @cankarm

**Comment by cankarm** [comment]
I think that this is an appropriate enhancement that will need to be done anyway at some point.
